"""empty message

Revision ID: 026fdd625196
Revises: 
Create Date: 2023-03-13 12:38:55.383981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026fdd625196'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('circuitId', sa.Integer(), nullable=False),
    sa.Column('circuitRef', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('alt', sa.Integer(), nullable=True),
    sa.Column('url', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('circuitId')
    )
    op.create_table('constructors',
    sa.Column('constructorId', sa.Integer(), nullable=False),
    sa.Column('constructorRef', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('nationality', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('constructorId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('constructors')
    op.drop_table('circuits')
    # ### end Alembic commands ###
